Update build-and-push-docker-images.yml

diff --git a/.github/workflows/build-and-push-docker-images.yml b/.github/workflows/build-and-push-docker-images.yml
--- a/.github/workflows/build-and-push-docker-images.yml
+++ b/.github/workflows/build-and-push-docker-images.yml
@@ -85,25 +85,6 @@ jobs:
             description="A Docker image automatically built from the repo $GH_FULL_REPO_NAME."
           push: true
 
-      - name: Validate & Set GHCR Linking
-        id: validate_and_set_ghcr_linking
-        run: |
-          LINKED_REPO=$(gh api /user/packages/container/$REPO_NAME/repositories | jq --arg repo "$GH_FULL_REPO_NAME" '.repositories[] | select(.full_name == $repo)')
-          GH_REPOSITORY_id=${{ github.repository_id }}
-          if [[ -z "$LINKED_REPO" ]]; then
-            echo "Linking repository to GHCR package..."
-            
-            gh api --method PUT \
-              -H "Accept: application/vnd.github.v3+json" \
-              /user/packages/container/$REPO_NAME/repositories \
-              -f repository_id=$GH_REPOSITORY_id || {
-                echo "Failed to link repository to GHCR package!"
-                exit 1
-              }
-          
-            echo "Repository successfully linked to GHCR package."
-          fi
-
       - name: Check & Set GHCR Image Visibility
         id: check_and_set_visibility
         run: |
@@ -131,4 +112,23 @@ jobs:
             echo "Visibility updated to public."
           else
             echo "Visibility is already public. No changes needed."
+          fi
+
+      - name: Validate & Set GHCR Linking
+        id: validate_and_set_ghcr_linking
+        run: |
+          LINKED_REPO=$(gh api /user/packages/container/$REPO_NAME/repositories | jq --arg repo "$GH_FULL_REPO_NAME" '.repositories[] | select(.full_name == $repo)')
+          GH_REPOSITORY_id=${{ github.repository_id }}
+          if [[ -z "$LINKED_REPO" ]]; then
+            echo "Linking repository to GHCR package..."
+            
+            gh api --method PUT \
+              -H "Accept: application/vnd.github.v3+json" \
+              /user/packages/container/$REPO_NAME/repositories \
+              -f repository_id=$GH_REPOSITORY_id || {
+                echo "Failed to link repository to GHCR package!"
+                exit 1
+              }
+          
+            echo "Repository successfully linked to GHCR package."
           fi
